const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Follow,
		C3.Behaviors.Pin,
		C3.Behaviors.Car,
		C3.Behaviors.solid,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.bound,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.DrawingCanvas,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.Multiplayer,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.UserMedia,
		C3.Plugins.video,
		C3.Plugins.AJAX,
		C3.Plugins.Dictionary,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.EightDir,
		C3.Behaviors.Tween,
		C3.Plugins.SpeechRecognition,
		C3.Plugins.Json,
		C3.Plugins.C2WebSocket,
		C3.Plugins.BinaryData,
		C3.Plugins.HTMLElement,
		C3.Plugins.TextBox,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.video.Cnds.IsPlaying,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetWrapping,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.Text.Acts.TypewriterFinish,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.TextBox.Acts.SetPos,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.JavaScriptInEvents.DoYouSellSimCards_Event1_Act4,
		C3.JavaScriptInEvents.DoYouSellSimCards_Event1_Act5,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.TextBox.Cnds.CompareX,
		C3.JavaScriptInEvents.HowMuchDoesASimCard_Event1_Act4,
		C3.JavaScriptInEvents.HowMuchDoesASimCard_Event1_Act5,
		C3.JavaScriptInEvents.HowMuchIsTheFare_Event2_Act4,
		C3.JavaScriptInEvents.HowMuchIsTheFare_Event2_Act5,
		C3.JavaScriptInEvents.Misson7_whereCanChangeMoney_Event2_Act4,
		C3.JavaScriptInEvents.Misson7_whereCanChangeMoney_Event2_Act5,
		C3.JavaScriptInEvents.WhereCanBuySimCard_Event1_Act6,
		C3.JavaScriptInEvents.WhereCanBuySimCard_Event1_Act7,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.AbsoluteX,
		C3.Plugins.Touch.Exps.AbsoluteY,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.EightDir.Acts.SetVectorX,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.Sprite.Acts.SetAnimRepeatToFrame,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.System.Exps.int,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.JavaScriptInEvents.DoYouSellSimCards2_Event1_Act4,
		C3.JavaScriptInEvents.DoYouSellSimCards2_Event1_Act5,
		C3.JavaScriptInEvents.DoYouSellSimCards3_Event1_Act4,
		C3.JavaScriptInEvents.DoYouSellSimCards3_Event1_Act5,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetEffect,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.JavaScriptInEvents.AddCash2_Event2_Act14,
		C3.JavaScriptInEvents.AddCash2_Event2_Act15,
		C3.JavaScriptInEvents.HowMuchIsItInTotal2_Event6_Act3,
		C3.JavaScriptInEvents.HowMuchIsItInTotal2_Event6_Act4,
		C3.JavaScriptInEvents["---3_Event1_Act3"],
		C3.JavaScriptInEvents["---3_Event2_Act1"],
		C3.JavaScriptInEvents["---3_Event3_Act1"],
		C3.JavaScriptInEvents.HowToCareForClassmates2_Event2_Act15,
		C3.JavaScriptInEvents.HowToCareForClassmates2_Event2_Act16,
		C3.JavaScriptInEvents["HowMuchIsTwoHundredAndFifty(250)2_Event2_Act3"],
		C3.JavaScriptInEvents["HowMuchIsTwoHundredAndFifty(250)2_Event2_Act4"],
		C3.JavaScriptInEvents.WhereIsTheBuildingWhereTheDialogueClassesAreHeld2_Event2_Act3,
		C3.JavaScriptInEvents.WhereIsTheBuildingWhereTheDialogueClassesAreHeld2_Event2_Act4,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.JavaScriptInEvents["ExcuseMe,HowDoIGetToTheDormitory2_Event2_Act3"],
		C3.JavaScriptInEvents["ExcuseMe,HowDoIGetToTheDormitory2_Event2_Act4"],
		C3.JavaScriptInEvents["---4_Event1_Act1"],
		C3.JavaScriptInEvents["---4_Event1_Act2"],
		C3.JavaScriptInEvents.AddCash_Event2_Act18,
		C3.JavaScriptInEvents.AddCash_Event2_Act19,
		C3.JavaScriptInEvents.HowMuchIsItInTotal_Event2_Act4,
		C3.JavaScriptInEvents.HowMuchIsItInTotal_Event2_Act5,
		C3.JavaScriptInEvents["---_Event1_Act3"],
		C3.JavaScriptInEvents["---_Event2_Act1"],
		C3.JavaScriptInEvents["---_Event3_Act1"],
		C3.JavaScriptInEvents.HowToCareForClassmates_Event2_Act13,
		C3.JavaScriptInEvents.HowToCareForClassmates_Event2_Act14,
		C3.JavaScriptInEvents["HowMuchIsTwoHundredAndFifty(250)_Event2_Act4"],
		C3.JavaScriptInEvents["HowMuchIsTwoHundredAndFifty(250)_Event2_Act5"],
		C3.JavaScriptInEvents.WhereIsTheBuildingWhereTheDialogueClassesAreHeld_Event2_Act3,
		C3.JavaScriptInEvents.WhereIsTheBuildingWhereTheDialogueClassesAreHeld_Event2_Act4,
		C3.JavaScriptInEvents["ExcuseMe,HowDoIGetToTheDormitory_Event2_Act4"],
		C3.JavaScriptInEvents["ExcuseMe,HowDoIGetToTheDormitory_Event2_Act5"],
		C3.JavaScriptInEvents["---2_Event1_Act1"],
		C3.JavaScriptInEvents["---2_Event1_Act2"],
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.JavaScriptInEvents.CanIPayWith______Event1_Act4,
		C3.JavaScriptInEvents.CanIPayWith______Event1_Act5,
		C3.JavaScriptInEvents.CanITakePhotosOrVideos_Event1_Act4,
		C3.JavaScriptInEvents.CanITakePhotosOrVideos_Event1_Act5,
		C3.JavaScriptInEvents.HowMuchATicketCosts_Event1_Act4,
		C3.JavaScriptInEvents.HowMuchATicketCosts_Event1_Act5,
		C3.JavaScriptInEvents.IWant______Event1_Act4,
		C3.JavaScriptInEvents.IWant______Event1_Act5,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.JavaScriptInEvents["SelectBus1-1_Event1_Act4"],
		C3.JavaScriptInEvents["SelectBus1-1_Event1_Act5"],
		C3.JavaScriptInEvents["SelectBus1-2_Event1_Act4"],
		C3.JavaScriptInEvents["SelectBus1-2_Event1_Act5"],
		C3.JavaScriptInEvents["SelectBus1-3_Event1_Act4"],
		C3.JavaScriptInEvents["SelectBus1-3_Event1_Act5"],
		C3.JavaScriptInEvents["SelectBus1-4_Event1_Act4"],
		C3.JavaScriptInEvents["SelectBus1-4_Event1_Act5"],
		C3.JavaScriptInEvents.IWantToEat2_Event1_Act5,
		C3.JavaScriptInEvents.IWantToEat2_Event1_Act6,
		C3.JavaScriptInEvents["I'MHungry.(Spoken)_Event2_Act4"],
		C3.JavaScriptInEvents["I'MHungry.(Spoken)_Event2_Act5"],
		C3.JavaScriptInEvents["IWant_(Spoken)_Event2_Act4"],
		C3.JavaScriptInEvents["IWant_(Spoken)_Event2_Act5"],
		C3.JavaScriptInEvents["DescribeTheAppearance,Color_Event1_Act10"],
		C3.JavaScriptInEvents["DescribeTheAppearance,Color_Event1_Act11"],
		C3.JavaScriptInEvents["IWantAGlassOf_____(Speaking)_Event6_Act4"],
		C3.JavaScriptInEvents["IWantAGlassOf_____(Speaking)_Event6_Act5"],
		C3.JavaScriptInEvents.Saying_____IsMissing_Event1_Act4,
		C3.JavaScriptInEvents.Saying_____IsMissing_Event1_Act5,
		C3.JavaScriptInEvents["WhereIsTheSouvenirShop)Speaking_Event1_Act14"],
		C3.JavaScriptInEvents["WhereIsTheSouvenirShop)Speaking_Event1_Act15"],
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.JavaScriptInEvents.WhatAreTheyDoing_Event2_Act16,
		C3.JavaScriptInEvents.WhatAreTheyDoing_Event2_Act17,
		C3.JavaScriptInEvents.Drink_sugerNIce_Event1_Act4,
		C3.JavaScriptInEvents.Drink_sugerNIce_Event1_Act5
	];
};
self.C3_JsPropNameTable = [
	{Follow: 0},
	{Pin: 0},
	{path: 0},
	{Car: 0},
	{Sprite31: 0},
	{turningPoint: 0},
	{Sprite25: 0},
	{TurnLeft: 0},
	{TurnRight: 0},
	{goStraight: 0},
	{name2: 0},
	{Sprite40: 0},
	{Sprite41: 0},
	{Sprite46: 0},
	{Sprite47: 0},
	{Sprite51: 0},
	{Sprite206: 0},
	{Solid: 0},
	{Fade: 0},
	{npcs_speaking: 0},
	{name: 0},
	{OptionA: 0},
	{OptionB: 0},
	{OptionC: 0},
	{OptionD: 0},
	{Sprite20: 0},
	{DragDrop: 0},
	{BoundToLayout: 0},
	{tile_airport: 0},
	{tile_fade: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{TiledBG_airport: 0},
	{TiledBG_road: 0},
	{BG: 0},
	{TiledBackground10: 0},
	{TiledBackground11: 0},
	{TiledBackground12: 0},
	{TiledBackground13: 0},
	{TiledBackground14: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{TiledBackground5: 0},
	{TiledBackground6: 0},
	{TiledBackground7: 0},
	{TiledBackground8: 0},
	{TiledBackground9: 0},
	{TiledBackground15: 0},
	{TiledBackground17: 0},
	{TiledBackground16: 0},
	{Sprite39: 0},
	{Sprite57: 0},
	{TiledBackground18: 0},
	{TiledBackground19: 0},
	{TiledBackground23: 0},
	{TiledBackground24: 0},
	{TaiwanDollar: 0},
	{name5: 0},
	{EasyCard: 0},
	{creditCard: 0},
	{SIMCard: 0},
	{RoomCard: 0},
	{ID: 0},
	{bagbutton: 0},
	{bagbox: 0},
	{bagclose: 0},
	{phone: 0},
	{phonebox: 0},
	{phoneclose: 0},
	{set: 0},
	{setbox: 0},
	{setclose: 0},
	{Sprite16: 0},
	{voice: 0},
	{isRecording: 0},
	{MicButton: 0},
	{voice2: 0},
	{home: 0},
	{dist: 0},
	{Joystick: 0},
	{JoystickBG: 0},
	{Audio: 0},
	{Browser: 0},
	{drag: 0},
	{DrawingCanvas: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{Multiplayer: 0},
	{StoryArray: 0},
	{Touch: 0},
	{UserMedia: 0},
	{Video: 0},
	{AJAX: 0},
	{Dictionary: 0},
	{sliderVolume: 0},
	{volumeBar: 0},
	{Sprite: 0},
	{Button_Delete: 0},
	{Button_Play: 0},
	{CheckButton: 0},
	{close: 0},
	{CloseBox: 0},
	{again: 0},
	{next: 0},
	{volumeBar_sound: 0},
	{sliderVolume2: 0},
	{PlayerAppearance: 0},
	{PlayerName: 0},
	{MusicVolume: 0},
	{SFXVolume: 0},
	{Language: 0},
	{QuestProgress: 0},
	{DialogueProgress: 0},
	{LearnedWords: 0},
	{Cash: 0},
	{GameData: 0},
	{QA: 0},
	{LearnedData: 0},
	{next2: 0},
	{CHEN: 0},
	{voice3: 0},
	{next3: 0},
	{Sprite73: 0},
	{Sprite74: 0},
	{Sprite75: 0},
	{Sprite76: 0},
	{Sprite77: 0},
	{Sprite78: 0},
	{Sprite79: 0},
	{Sprite80: 0},
	{bread: 0},
	{milk: 0},
	{Sprite83: 0},
	{Sprite84: 0},
	{Sprite85: 0},
	{Sprite87: 0},
	{Sprite88: 0},
	{Sprite89: 0},
	{Sprite91: 0},
	{Sprite92: 0},
	{Sprite93: 0},
	{fruit01: 0},
	{fruit02: 0},
	{fruit03: 0},
	{fruit04: 0},
	{fruit05: 0},
	{fruit06: 0},
	{fruit07: 0},
	{fruit08: 0},
	{fruit09: 0},
	{SupportedText: 0},
	{InterimResult: 0},
	{FinalResult: 0},
	{EventsText: 0},
	{Button: 0},
	{Mission1: 0},
	{Mission2: 0},
	{Mission3_ask1: 0},
	{Mission3_ask2: 0},
	{Mission3_SIM: 0},
	{Mission4_ATM: 0},
	{Sprite139: 0},
	{m2_2_2: 0},
	{m2_2_1: 0},
	{Sprite105: 0},
	{Sprite106: 0},
	{Sprite107: 0},
	{Sprite108: 0},
	{Sprite109: 0},
	{Sprite110: 0},
	{Sprite111: 0},
	{Sprite112: 0},
	{Sprite113: 0},
	{Sprite114: 0},
	{Sprite115: 0},
	{Clinic_Skin: 0},
	{Sprite117: 0},
	{Sprite118: 0},
	{Sprite119: 0},
	{Sprite120: 0},
	{Sprite123: 0},
	{Clinic_Eye: 0},
	{Clinic_Teeth: 0},
	{Clinic_EarNoseThroat: 0},
	{m2_1: 0},
	{Sprite10: 0},
	{Sprite124: 0},
	{Start: 0},
	{SentencesBox: 0},
	{DialogueText: 0},
	{Sentencesnext: 0},
	{step: 0},
	{"8Direction": 0},
	{Sprite3: 0},
	{Doorleft: 0},
	{Doorright: 0},
	{SentencesText01: 0},
	{Text: 0},
	{Sprite11: 0},
	{Sprite19: 0},
	{Sprite24: 0},
	{Sprite29: 0},
	{ErrorText: 0},
	{text1: 0},
	{TextBox_A: 0},
	{newmessage: 0},
	{newmessagebutton: 0},
	{chose1: 0},
	{chose2: 0},
	{Sprite30: 0},
	{Sprite36: 0},
	{Text2: 0},
	{Text3: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{messagebutton: 0},
	{Sprite14: 0},
	{Text4: 0},
	{Text5: 0},
	{Sprite21: 0},
	{Sprite28: 0},
	{Sprite32: 0},
	{Text6: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Tween: 0},
	{tasknews: 0},
	{Sprite2: 0},
	{Sprite15: 0},
	{Sprite37: 0},
	{Sprite38: 0},
	{Sprite42: 0},
	{ResultText: 0},
	{Sprite43: 0},
	{Sprite44: 0},
	{Sprite45: 0},
	{Sprite48: 0},
	{Sprite49: 0},
	{Sprite50: 0},
	{missontext: 0},
	{Sprite53: 0},
	{Text9: 0},
	{Text10: 0},
	{select_traffic: 0},
	{Sprite9: 0},
	{Sprite54: 0},
	{Sprite55: 0},
	{Sprite56: 0},
	{Sprite8: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{cardbox: 0},
	{cardtext: 0},
	{Sprite59: 0},
	{Sprite60: 0},
	{Sprite7: 0},
	{Sprite67: 0},
	{Sprite68: 0},
	{name8: 0},
	{"500x1": 0},
	{"100x3": 0},
	{name9: 0},
	{Door1: 0},
	{Door2: 0},
	{Door3: 0},
	{Door4: 0},
	{RoomNumber: 0},
	{Text7: 0},
	{Sprite69: 0},
	{Text11_CH: 0},
	{A_L1: 0},
	{B_L1: 0},
	{C_L1: 0},
	{Sprite70: 0},
	{teach01: 0},
	{Sprite71: 0},
	{Sprite72: 0},
	{Text12: 0},
	{missioncompleted_box: 0},
	{TextBox_B: 0},
	{Sprite26: 0},
	{Text14: 0},
	{Sprite5: 0},
	{Text15: 0},
	{FeedbackText: 0},
	{cardoor: 0},
	{taxidoor: 0},
	{Sprite66: 0},
	{Text16: 0},
	{Sprite81: 0},
	{Sprite82: 0},
	{Sprite86: 0},
	{Sprite90: 0},
	{Sprite94: 0},
	{Sprite95: 0},
	{Taiwan: 0},
	{NewTaipei: 0},
	{Sprite96: 0},
	{Sprite97: 0},
	{Sprite98: 0},
	{Sprite4: 0},
	{Sprite99: 0},
	{SpeechRecognition: 0},
	{Sprite100: 0},
	{Text17: 0},
	{Sprite101: 0},
	{Sprite102: 0},
	{Sprite121: 0},
	{Sprite122: 0},
	{Text18: 0},
	{Sprite125: 0},
	{Sprite126: 0},
	{Sprite127: 0},
	{Sprite128: 0},
	{Sprite129: 0},
	{Text19: 0},
	{Sprite130: 0},
	{Sprite131: 0},
	{Sprite132: 0},
	{Text20: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite103: 0},
	{Sprite104: 0},
	{Sprite116: 0},
	{history3: 0},
	{history4: 0},
	{history1: 0},
	{history2: 0},
	{BG_ALL: 0},
	{Sprite142: 0},
	{Sprite143: 0},
	{Sprite144: 0},
	{JSON: 0},
	{Text21: 0},
	{TextBox_anser: 0},
	{WebSocketDict: 0},
	{Debug_AJAX_Status: 0},
	{Text_AJAX_LastData: 0},
	{Text_Text_Result: 0},
	{Sprite138: 0},
	{shop00: 0},
	{shop05: 0},
	{shop03: 0},
	{shop04: 0},
	{shop01: 0},
	{shop02: 0},
	{Sprite149: 0},
	{Sprite150: 0},
	{Sprite151: 0},
	{p1: 0},
	{p2: 0},
	{p5: 0},
	{p4: 0},
	{p3: 0},
	{shop06: 0},
	{Sprite158: 0},
	{Sprite140: 0},
	{TiledBackground20: 0},
	{Sprite145: 0},
	{Sprite146: 0},
	{Sprite147: 0},
	{Sprite148: 0},
	{Sprite159: 0},
	{WebSocket: 0},
	{BinaryData: 0},
	{personbutton: 0},
	{bookbutton: 0},
	{teambutton: 0},
	{homebutton: 0},
	{notebutton: 0},
	{HTMLElement: 0},
	{HTMLElement2: 0},
	{TiledBackground21: 0},
	{Text22: 0},
	{Sprite160: 0},
	{Sprite161: 0},
	{Sentencesnext2: 0},
	{Sprite137: 0},
	{school_introtext: 0},
	{TextInput: 0},
	{Array_choose: 0},
	{Sprite162: 0},
	{Sprite163: 0},
	{Sprite164: 0},
	{Sprite165: 0},
	{Sprite166: 0},
	{Sprite167: 0},
	{Sprite168: 0},
	{Sprite169: 0},
	{Sprite170: 0},
	{Sprite171: 0},
	{Sprite172: 0},
	{Sprite173: 0},
	{Sprite174: 0},
	{Sprite175: 0},
	{Sprite176: 0},
	{Sprite177: 0},
	{Text23: 0},
	{TiledBackground22: 0},
	{Sprite178: 0},
	{Sprite179: 0},
	{Sprite180: 0},
	{Sprite181: 0},
	{Sprite182: 0},
	{Sprite183_ButtonVocabulary: 0},
	{Sprite184_ButtonGrammar: 0},
	{Sprite185_ButtonSituation: 0},
	{TextVocabulary: 0},
	{TextGrammar: 0},
	{Text24: 0},
	{Text25: 0},
	{ppt: 0},
	{Sprite184: 0},
	{Sprite185: 0},
	{Sprite186: 0},
	{Sprite188: 0},
	{NoteText: 0},
	{Sprite189: 0},
	{Sprite190: 0},
	{Sprite191: 0},
	{Sprite192: 0},
	{Sprite193: 0},
	{Sprite133: 0},
	{Sprite134: 0},
	{Bill500: 0},
	{Sprite135: 0},
	{Bill1000: 0},
	{Sprite136: 0},
	{Coin1: 0},
	{Coin5: 0},
	{Sprite194: 0},
	{Coin10: 0},
	{Sprite195: 0},
	{Coin50: 0},
	{Sprite196: 0},
	{Bill100: 0},
	{Sprite197: 0},
	{Sprite187: 0},
	{Sprite198: 0},
	{p6: 0},
	{chose3: 0},
	{Sprite152: 0},
	{Sprite153: 0},
	{Sprite154: 0},
	{foodchose11: 0},
	{foodchose12: 0},
	{foodchose13: 0},
	{foodchose14: 0},
	{foodchose15: 0},
	{foodchose16: 0},
	{foodchose21: 0},
	{foodchose22: 0},
	{foodchose23: 0},
	{foodchose24: 0},
	{foodchose25: 0},
	{foodchose26: 0},
	{foodchose31: 0},
	{foodchose32: 0},
	{foodchose33: 0},
	{foodchose34: 0},
	{foodchose35: 0},
	{foodchose36: 0},
	{foodchose41: 0},
	{foodchose42: 0},
	{foodchose43: 0},
	{foodchose44: 0},
	{foodchose45: 0},
	{foodchose46: 0},
	{foodchose51: 0},
	{foodchose52: 0},
	{foodchose53: 0},
	{foodchose54: 0},
	{foodchose55: 0},
	{foodchose56: 0},
	{chose4: 0},
	{chose5: 0},
	{chose6: 0},
	{D_L1: 0},
	{Sprite155: 0},
	{Sprite156: 0},
	{Text11_EN: 0},
	{Text26: 0},
	{notepage: 0},
	{Sprite208: 0},
	{shop1: 0},
	{Sprite209: 0},
	{Sprite210: 0},
	{foodchose17: 0},
	{foodchose18: 0},
	{Sprite207: 0},
	{drink_suger0: 0},
	{drink_ice0: 0},
	{drink_suger1: 0},
	{drink_suger2: 0},
	{drink_suger3: 0},
	{drink_suger4: 0},
	{drink_ice1: 0},
	{drink_ice2: 0},
	{drink_ice3: 0},
	{drink_ice4: 0},
	{Text27: 0},
	{Text28: 0},
	{Sprite183: 0},
	{Sprite211: 0},
	{Sprite212: 0},
	{Text11_CH2: 0},
	{ppt1: 0},
	{ppt2: 0},
	{ppt3: 0},
	{ppt4: 0},
	{ppt5: 0},
	{ppt6: 0},
	{ppt7: 0},
	{ppt8: 0},
	{ppt9: 0},
	{mission_title: 0},
	{pronunce: 0},
	{Sprite213: 0},
	{opentext2: 0},
	{SentencesText2: 0},
	{Text11_CH3: 0},
	{Text11_CH4: 0},
	{Text11_CH5: 0},
	{Sprite214: 0},
	{missionbox: 0},
	{Video2: 0},
	{missioncompleted_box2: 0},
	{joy: 0},
	{Options_people: 0},
	{Options_trans: 0},
	{Options_cards: 0},
	{Options_money: 0},
	{Options_doors: 0},
	{Missions: 0},
	{foods: 0},
	{CorrectAnswer02: 0},
	{CorrectAnswer49: 0},
	{CorrectAnswer50: 0},
	{CorrectAnswer55: 0},
	{CorrectAnswer51: 0},
	{CorrectAnswer52: 0},
	{CorrectAnswer53: 0},
	{CorrectAnswer54: 0},
	{CorrectAnswer56: 0},
	{CorrectAnswer58: 0},
	{CorrectAnswer59: 0},
	{CorrectAnswer60: 0},
	{CorrectAnswer3: 0},
	{CorrectAnswer63: 0},
	{CorrectAnswer64: 0},
	{CorrectAnswer2: 0},
	{CorrectAnswer57: 0},
	{CorrectAnswer61: 0},
	{CorrectAnswer62: 0},
	{misson4_test: 0},
	{SelectedOption5: 0},
	{SelectedOption8: 0},
	{PlayerText: 0},
	{ServerURL: 0},
	{CorrectAnswer01: 0},
	{CorrectAnswer48: 0},
	{CorrectAnswer42: 0},
	{CorrectAnswer43: 0},
	{CorrectAnswer44: 0},
	{CorrectAnswer45: 0},
	{CorrectAnswer46: 0},
	{CorrectAnswer47: 0},
	{startTouchX2: 0},
	{startTouchY2: 0},
	{startScrollX2: 0},
	{startScrollY2: 0},
	{dragging2: 0},
	{SelectedOption: 0},
	{click: 0},
	{HowToPlay: 0},
	{SelectedOption6: 0},
	{CurrentLineIndex_0: 0},
	{PlayerPosX: 0},
	{PlayerPosY: 0},
	{CurrentMission: 0},
	{Mission1Completed: 0},
	{Mission2Completed: 0},
	{Mission3Completed: 0},
	{Mission4Completed: 0},
	{Mission5Completed: 0},
	{startTouchX4: 0},
	{startTouchY4: 0},
	{startScrollX4: 0},
	{startScrollY4: 0},
	{dragging4: 0},
	{SelectedOption9: 0},
	{startTouchX3: 0},
	{startTouchY3: 0},
	{startScrollX3: 0},
	{startScrollY3: 0},
	{dragging3: 0},
	{SelectedOption2: 0},
	{SelectedOption7: 0},
	{day: 0},
	{start: 0},
	{day1completed: 0},
	{day2completed: 0},
	{day3completed: 0},
	{day4completed: 0},
	{volume: 0},
	{CurrentIndex: 0},
	{"0CurrentDialogueIndex": 0},
	{EN: 0},
	{CurrentLanguage: 0},
	{CH: 0},
	{ENframe: 0},
	{CorrectAnswer11: 0},
	{CorrectAnswer12: 0},
	{CurrentDialogueIndex36: 0},
	{CurrentDialogueIndex39: 0},
	{CurrentDialogueIndex42: 0},
	{CurrentDialogueIndex44: 0},
	{CurrentLineIndex_1: 0},
	{has_shown_dialogue: 0},
	{PlayerPosX6: 0},
	{PlayerPosY6: 0},
	{CurrentMission6: 0},
	{Mission1Completed6: 0},
	{Mission2Completed6: 0},
	{Mission3Completed6: 0},
	{Mission4Completed6: 0},
	{Mission５Completed2: 0},
	{IsCorrectlyPlaced6: 0},
	{CorrectAnswers4: 0},
	{CurrentDialogueIndex30: 0},
	{CurrentStoryID2: 0},
	{CurrentDialogueIndex2: 0},
	{Branch_A_Selected2: 0},
	{Branch_B_Selected2: 0},
	{SelectedBranch2: 0},
	{Quest1_Completed2: 0},
	{Quest2_Completed2: 0},
	{currentSentenceIndex_taxi5: 0},
	{PlayerPosX5: 0},
	{PlayerPosY5: 0},
	{CurrentMission5: 0},
	{Mission1Completed5: 0},
	{Mission2Completed5: 0},
	{Mission3Completed5: 0},
	{Mission4Completed5: 0},
	{Mission5Completed3: 0},
	{Mission6Completed3: 0},
	{Mission7Completed3: 0},
	{Mission8Completed3: 0},
	{Mission9Completed3: 0},
	{Currentbuild3: 0},
	{Build5: 0},
	{Build6: 0},
	{Build7: 0},
	{Build8: 0},
	{IsCorrectlyPlaced7: 0},
	{CorrectAnswer36: 0},
	{CorrectAnswer37: 0},
	{recordedBlob2: 0},
	{Transcription2: 0},
	{isRecording2: 0},
	{audioBlob2: 0},
	{socket2: 0},
	{TranscriptionText2: 0},
	{CorrectAnswer38: 0},
	{CorrectAnswer39: 0},
	{CorrectAnswer40: 0},
	{leftright2: 0},
	{CorrectAnswer41: 0},
	{CurrentDialogueIndex6: 0},
	{CurrentDialogueIndex11: 0},
	{CurrentDialogueIndex17: 0},
	{CurrentDialogueIndex19: 0},
	{finish3: 0},
	{CurrentDialogueIndex55: 0},
	{CurrentDialogueIndex56: 0},
	{finish4: 0},
	{CurrentDialogueIndex85: 0},
	{IsCorrectlyPlaced2: 0},
	{CorrectAnswers2: 0},
	{CurrentDialogueIndex29: 0},
	{CurrentStoryID: 0},
	{CurrentDialogueIndex: 0},
	{Branch_A_Selected: 0},
	{Branch_B_Selected: 0},
	{SelectedBranch: 0},
	{Quest1_Completed: 0},
	{Quest2_Completed: 0},
	{currentSentenceIndex_taxi2: 0},
	{PlayerPosX2: 0},
	{PlayerPosY2: 0},
	{CurrentMission2: 0},
	{Mission1Completed2: 0},
	{Mission2Completed2: 0},
	{Mission3Completed2: 0},
	{Mission4Completed2: 0},
	{Mission5Completed2: 0},
	{Mission6Completed2: 0},
	{Mission7Completed2: 0},
	{Mission8Completed2: 0},
	{Mission9Completed2: 0},
	{Currentbuild: 0},
	{Build1: 0},
	{Build2: 0},
	{Build3: 0},
	{Build4: 0},
	{IsCorrectlyPlaced3: 0},
	{CorrectAnswer4: 0},
	{CorrectAnswer65: 0},
	{CorrectAnswer66: 0},
	{CorrectAnswer67: 0},
	{CorrectAnswer68: 0},
	{CorrectAnswer5: 0},
	{CorrectAnswer69: 0},
	{CorrectAnswer70: 0},
	{recordedBlob: 0},
	{Transcription: 0},
	{audioBlob: 0},
	{socket: 0},
	{TranscriptionText: 0},
	{CorrectAnswer6: 0},
	{CorrectAnswer71: 0},
	{CorrectAnswer72: 0},
	{CorrectAnswer13: 0},
	{CorrectAnswer73: 0},
	{CorrectAnswer74: 0},
	{CorrectAnswer14: 0},
	{leftright: 0},
	{CorrectAnswer15: 0},
	{CorrectAnswer75: 0},
	{CorrectAnswer76: 0},
	{CorrectAnswer77: 0},
	{CurrentDialogueIndex5: 0},
	{CurrentDialogueIndex10: 0},
	{CurrentDialogueIndex12: 0},
	{finish: 0},
	{CurrentDialogueIndex54: 0},
	{finish2: 0},
	{CurrentDialogueIndex84: 0},
	{CorrectAnswer22: 0},
	{CorrectAnswer82: 0},
	{CorrectAnswer83: 0},
	{CorrectAnswer84: 0},
	{CorrectAnswer85: 0},
	{CorrectAnswer86: 0},
	{CorrectAnswer16: 0},
	{CorrectAnswer87: 0},
	{CorrectAnswer88: 0},
	{CorrectAnswer89: 0},
	{CorrectAnswer90: 0},
	{CorrectAnswer91: 0},
	{DialogueStage: 0},
	{IsCorrectlyPlaced4: 0},
	{AnswerAttempts: 0},
	{CorrectAnswer: 0},
	{IsCorrectAnswer: 0},
	{CorrectAnswer21: 0},
	{CorrectAnswer78: 0},
	{CorrectAnswer79: 0},
	{CorrectAnswer80: 0},
	{CorrectAnswer81: 0},
	{CorrectAnswer27: 0},
	{CorrectAnswer29: 0},
	{CorrectAnswer30: 0},
	{CorrectAnswer92: 0},
	{CorrectAnswer93: 0},
	{foodchoice_noodle: 0},
	{foodchoice_rice: 0},
	{foodchoice_soup: 0},
	{foodchoice_snack: 0},
	{foodchoice_dessert: 0},
	{foodchoice_noodle2: 0},
	{foodchoice_rice2: 0},
	{foodchoice_soup2: 0},
	{foodchoice_snack2: 0},
	{foodchoice_dessert2: 0},
	{foodchoice_noodle3: 0},
	{foodchoice_rice3: 0},
	{foodchoice_soup3: 0},
	{foodchoice_snack3: 0},
	{foodchoice_dessert3: 0},
	{foodchoice_noodle4: 0},
	{foodchoice_rice4: 0},
	{foodchoice_soup4: 0},
	{foodchoice_snack4: 0},
	{foodchoice_dessert4: 0},
	{foodchoice_noodle5: 0},
	{foodchoice_rice5: 0},
	{foodchoice_soup5: 0},
	{foodchoice_snack5: 0},
	{foodchoice_dessert5: 0},
	{foodchoice_noodle6: 0},
	{foodchoice_rice6: 0},
	{foodchoice_soup6: 0},
	{foodchoice_snack6: 0},
	{foodchoice_dessert6: 0},
	{"0count": 0},
	{text2: 0},
	{text3: 0},
	{read1: 0},
	{read2: 0},
	{read3: 0},
	{currentSentenceIndex_taxi3: 0},
	{PlayerPosX3: 0},
	{PlayerPosY3: 0},
	{CurrentMission3: 0},
	{Mission1Completed3: 0},
	{Mission2Completed3: 0},
	{Mission3Completed3: 0},
	{Mission4Completed3: 0},
	{Mission５Completed3: 0},
	{Completedbuild1: 0},
	{Completedbuild2: 0},
	{Completedbuild3: 0},
	{Completedbuild4: 0},
	{Currentbuild2: 0},
	{Completedhistory1: 0},
	{Completedhistory2: 0},
	{Completedhistory3: 0},
	{Completedhistory4: 0},
	{Currenthistory: 0},
	{CurrentDialogueIndex21: 0},
	{CurrentDialogueIndex27: 0},
	{IsCorrectlyPlaced5: 0},
	{CorrectAnswers3: 0},
	{SelectedOption11: 0},
	{CorrectAnswer17: 0},
	{CorrectAnswer31: 0},
	{CorrectAnswer32: 0},
	{CorrectAnswer106: 0},
	{CorrectAnswer18: 0},
	{CorrectAnswer107: 0},
	{CorrectAnswer19: 0},
	{CorrectAnswer20: 0},
	{CorrectAnswer26: 0},
	{CorrectAnswer261: 0},
	{CorrectAnswer262: 0},
	{CorrectAnswer263: 0},
	{CorrectAnswer264: 0},
	{CorrectAnswer265: 0},
	{CorrectAnswer266: 0},
	{foodchoice_Breakfast1: 0},
	{foodchoice_Breakfast2: 0},
	{foodchoice_Breakfast3: 0},
	{foodchoice_Breakfast4: 0},
	{foodchoice_Breakfast5: 0},
	{foodchoice_Breakfast6: 0},
	{foodchoice_Breakfast7: 0},
	{foodchoice_Breakfast8: 0},
	{foodchoice_drink1: 0},
	{foodchoice_drink2: 0},
	{foodchoice_drink3: 0},
	{foodchoice_drink4: 0},
	{sugertext: 0},
	{icetext: 0},
	{drinktext: 0},
	{suger: 0},
	{ice: 0},
	{CorrectAnswer7: 0},
	{CorrectAnswer94: 0},
	{CorrectAnswer95: 0},
	{CorrectAnswer8: 0},
	{CurrentDialogueIndex13: 0},
	{CorrectAnswer24: 0},
	{CorrectAnswer9: 0},
	{CorrectAnswer103: 0},
	{CorrectAnswer104: 0},
	{CorrectAnswer105: 0},
	{CorrectAnswer33: 0},
	{CorrectAnswer34: 0},
	{CorrectAnswer35: 0},
	{CorrectAnswer23: 0},
	{CorrectAnswer101: 0},
	{CorrectAnswer102: 0},
	{CorrectAnswer25: 0},
	{CorrectAnswer98: 0},
	{CorrectAnswer99: 0},
	{CorrectAnswer100: 0},
	{CurrentDialogueIndex100: 0},
	{SelectedOption12: 0},
	{currentSentenceIndex_taxi4: 0},
	{PlayerPosX4: 0},
	{PlayerPosY4: 0},
	{CurrentMission4: 0},
	{Mission1Completed4: 0},
	{Mission2Completed4: 0},
	{Mission3Completed4: 0},
	{Mission4Completed4: 0},
	{Mission5Completed4: 0},
	{Mission6Completed4: 0},
	{Mission7Completed4: 0},
	{A: 0},
	{B: 0},
	{AB: 0},
	{true: 0},
	{false: 0},
	{"1dollar": 0},
	{"5dollar": 0},
	{"10dollar": 0},
	{"50dollar": 0},
	{"100dollar": 0},
	{"500dollar": 0},
	{"1000dollar": 0},
	{TotalPrice: 0},
	{PaidAmount: 0},
	{ChangeAmount: 0},
	{A2: 0},
	{B2: 0},
	{AB2: 0},
	{CorrectAnswer28: 0},
	{CorrectAnswer96: 0},
	{CorrectAnswer97: 0},
	{CurrentDialogueIndex97: 0},
	{A3: 0},
	{B3: 0},
	{AB3: 0},
	{CurrentDialogueIndex15: 0},
	{true4: 0},
	{false4: 0},
	{"1dollar2": 0},
	{"5dollar2": 0},
	{"10dollar2": 0},
	{"50dollar2": 0},
	{"100dollar2": 0},
	{"500dollar2": 0},
	{"1000dollar2": 0},
	{TotalPrice2: 0},
	{PaidAmount2: 0},
	{ChangeAmount2: 0},
	{page: 0},
	{CurrentIndex0: 0},
	{true2: 0},
	{false2: 0},
	{ppt_page: 0},
	{ppt_Layout: 0},
	{true3: 0},
	{false3: 0},
	{Dragging_Map: 0},
	{Dragging_leftright: 0},
	{Click_menu: 0},
	{Click_dialogue: 0},
	{Click_note: 0},
	{Click_note2: 0}
];

self.InstanceType = {
	path: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	turningPoint: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	TurnLeft: class extends self.ISpriteInstance {},
	TurnRight: class extends self.ISpriteInstance {},
	goStraight: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	Sprite206: class extends self.ISpriteInstance {},
	npcs_speaking: class extends self.ISpriteInstance {},
	OptionA: class extends self.ISpriteInstance {},
	OptionB: class extends self.ISpriteInstance {},
	OptionC: class extends self.ISpriteInstance {},
	OptionD: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	tile_airport: class extends self.ITiledBackgroundInstance {},
	tile_fade: class extends self.ITiledBackgroundInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBG_airport: class extends self.ITiledBackgroundInstance {},
	TiledBG_road: class extends self.ITiledBackgroundInstance {},
	BG: class extends self.ITiledBackgroundInstance {},
	TiledBackground10: class extends self.ITiledBackgroundInstance {},
	TiledBackground11: class extends self.ITiledBackgroundInstance {},
	TiledBackground12: class extends self.ITiledBackgroundInstance {},
	TiledBackground13: class extends self.ITiledBackgroundInstance {},
	TiledBackground14: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	TiledBackground9: class extends self.ITiledBackgroundInstance {},
	TiledBackground15: class extends self.ITiledBackgroundInstance {},
	TiledBackground17: class extends self.ITiledBackgroundInstance {},
	TiledBackground16: class extends self.ITiledBackgroundInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	TiledBackground18: class extends self.ITiledBackgroundInstance {},
	TiledBackground19: class extends self.ITiledBackgroundInstance {},
	TiledBackground23: class extends self.ITiledBackgroundInstance {},
	TiledBackground24: class extends self.ITiledBackgroundInstance {},
	TaiwanDollar: class extends self.ISpriteInstance {},
	EasyCard: class extends self.ISpriteInstance {},
	creditCard: class extends self.ISpriteInstance {},
	SIMCard: class extends self.ISpriteInstance {},
	RoomCard: class extends self.ISpriteInstance {},
	ID: class extends self.ISpriteInstance {},
	bagbutton: class extends self.ISpriteInstance {},
	bagbox: class extends self.ISpriteInstance {},
	bagclose: class extends self.ISpriteInstance {},
	phone: class extends self.ISpriteInstance {},
	phonebox: class extends self.ISpriteInstance {},
	phoneclose: class extends self.ISpriteInstance {},
	set: class extends self.ISpriteInstance {},
	setbox: class extends self.ISpriteInstance {},
	setclose: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	voice: class extends self.ISpriteInstance {},
	MicButton: class extends self.ISpriteInstance {},
	voice2: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	Joystick: class extends self.ISpriteInstance {},
	JoystickBG: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	drag: class extends self.ISpriteInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Multiplayer: class extends self.IInstance {},
	StoryArray: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	UserMedia: class extends self.IWorldInstance {},
	Video: class extends self.IWorldInstance {},
	AJAX: class extends self.IInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	sliderVolume: class extends self.ISpriteInstance {},
	volumeBar: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Button_Delete: class extends self.ISpriteInstance {},
	Button_Play: class extends self.ISpriteInstance {},
	CheckButton: class extends self.ISpriteInstance {},
	close: class extends self.ISpriteInstance {},
	CloseBox: class extends self.ISpriteInstance {},
	again: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	volumeBar_sound: class extends self.ISpriteInstance {},
	sliderVolume2: class extends self.ISpriteInstance {},
	GameData: class extends self.IDictionaryInstance {},
	QA: class extends self.ISpriteInstance {},
	LearnedData: class extends self.IDictionaryInstance {},
	next2: class extends self.ISpriteInstance {},
	CHEN: class extends self.ISpriteInstance {},
	voice3: class extends self.ISpriteInstance {},
	next3: class extends self.ISpriteInstance {},
	Sprite73: class extends self.ISpriteInstance {},
	Sprite74: class extends self.ISpriteInstance {},
	Sprite75: class extends self.ISpriteInstance {},
	Sprite76: class extends self.ISpriteInstance {},
	Sprite77: class extends self.ISpriteInstance {},
	Sprite78: class extends self.ISpriteInstance {},
	Sprite79: class extends self.ISpriteInstance {},
	Sprite80: class extends self.ISpriteInstance {},
	bread: class extends self.ISpriteInstance {},
	milk: class extends self.ISpriteInstance {},
	Sprite83: class extends self.ISpriteInstance {},
	Sprite84: class extends self.ISpriteInstance {},
	Sprite85: class extends self.ISpriteInstance {},
	Sprite87: class extends self.ISpriteInstance {},
	Sprite88: class extends self.ISpriteInstance {},
	Sprite89: class extends self.ISpriteInstance {},
	Sprite91: class extends self.ISpriteInstance {},
	Sprite92: class extends self.ISpriteInstance {},
	Sprite93: class extends self.ISpriteInstance {},
	fruit01: class extends self.ISpriteInstance {},
	fruit02: class extends self.ISpriteInstance {},
	fruit03: class extends self.ISpriteInstance {},
	fruit04: class extends self.ISpriteInstance {},
	fruit05: class extends self.ISpriteInstance {},
	fruit06: class extends self.ISpriteInstance {},
	fruit07: class extends self.ISpriteInstance {},
	fruit08: class extends self.ISpriteInstance {},
	fruit09: class extends self.ISpriteInstance {},
	SupportedText: class extends self.ITextInstance {},
	InterimResult: class extends self.ITextInstance {},
	FinalResult: class extends self.ITextInstance {},
	EventsText: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	Mission1: class extends self.ISpriteInstance {},
	Mission2: class extends self.ISpriteInstance {},
	Mission3_ask1: class extends self.ISpriteInstance {},
	Mission3_ask2: class extends self.ISpriteInstance {},
	Mission3_SIM: class extends self.ISpriteInstance {},
	Mission4_ATM: class extends self.ISpriteInstance {},
	Sprite139: class extends self.ISpriteInstance {},
	m2_2_2: class extends self.ISpriteInstance {},
	m2_2_1: class extends self.ISpriteInstance {},
	Sprite105: class extends self.ISpriteInstance {},
	Sprite106: class extends self.ISpriteInstance {},
	Sprite107: class extends self.ISpriteInstance {},
	Sprite108: class extends self.ISpriteInstance {},
	Sprite109: class extends self.ISpriteInstance {},
	Sprite110: class extends self.ISpriteInstance {},
	Sprite111: class extends self.ISpriteInstance {},
	Sprite112: class extends self.ISpriteInstance {},
	Sprite113: class extends self.ISpriteInstance {},
	Sprite114: class extends self.ISpriteInstance {},
	Sprite115: class extends self.ISpriteInstance {},
	Clinic_Skin: class extends self.ISpriteInstance {},
	Sprite117: class extends self.ISpriteInstance {},
	Sprite118: class extends self.ISpriteInstance {},
	Sprite119: class extends self.ISpriteInstance {},
	Sprite120: class extends self.ISpriteInstance {},
	Sprite123: class extends self.ISpriteInstance {},
	Clinic_Eye: class extends self.ISpriteInstance {},
	Clinic_Teeth: class extends self.ISpriteInstance {},
	Clinic_EarNoseThroat: class extends self.ISpriteInstance {},
	m2_1: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite124: class extends self.ISpriteInstance {},
	Start: class extends self.ISpriteInstance {},
	SentencesBox: class extends self.ISpriteInstance {},
	DialogueText: class extends self.ITextInstance {},
	Sentencesnext: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Doorleft: class extends self.ISpriteInstance {},
	Doorright: class extends self.ISpriteInstance {},
	SentencesText01: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	ErrorText: class extends self.ITextInstance {},
	TextBox_A: class extends self.ITextInstance {},
	newmessage: class extends self.ISpriteInstance {},
	newmessagebutton: class extends self.ISpriteInstance {},
	chose1: class extends self.ITextInstance {},
	chose2: class extends self.ITextInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	messagebutton: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Text6: class extends self.ITextInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	tasknews: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	ResultText: class extends self.ITextInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	missontext: class extends self.ITextInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	Text9: class extends self.ITextInstance {},
	Text10: class extends self.ITextInstance {},
	select_traffic: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	cardbox: class extends self.ISpriteInstance {},
	cardtext: class extends self.ITextInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	Sprite60: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite67: class extends self.ISpriteInstance {},
	Sprite68: class extends self.ISpriteInstance {},
	_500x1: class extends self.ISpriteInstance {},
	_100x3: class extends self.ISpriteInstance {},
	Door1: class extends self.ISpriteInstance {},
	Door2: class extends self.ISpriteInstance {},
	Door3: class extends self.ISpriteInstance {},
	Door4: class extends self.ISpriteInstance {},
	RoomNumber: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {},
	Sprite69: class extends self.ISpriteInstance {},
	Text11_CH: class extends self.ITextInstance {},
	A_L1: class extends self.ISpriteInstance {},
	B_L1: class extends self.ISpriteInstance {},
	C_L1: class extends self.ISpriteInstance {},
	Sprite70: class extends self.ISpriteInstance {},
	teach01: class extends self.ITiledBackgroundInstance {},
	Sprite71: class extends self.ISpriteInstance {},
	Sprite72: class extends self.ISpriteInstance {},
	Text12: class extends self.ITextInstance {},
	missioncompleted_box: class extends self.ISpriteInstance {},
	TextBox_B: class extends self.ITextInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Text14: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Text15: class extends self.ITextInstance {},
	FeedbackText: class extends self.ITextInstance {},
	cardoor: class extends self.ISpriteInstance {},
	taxidoor: class extends self.ISpriteInstance {},
	Sprite66: class extends self.ISpriteInstance {},
	Text16: class extends self.ITextInstance {},
	Sprite81: class extends self.ISpriteInstance {},
	Sprite82: class extends self.ISpriteInstance {},
	Sprite86: class extends self.ISpriteInstance {},
	Sprite90: class extends self.ISpriteInstance {},
	Sprite94: class extends self.ISpriteInstance {},
	Sprite95: class extends self.ISpriteInstance {},
	Taiwan: class extends self.ISpriteInstance {},
	NewTaipei: class extends self.ISpriteInstance {},
	Sprite96: class extends self.ISpriteInstance {},
	Sprite97: class extends self.ISpriteInstance {},
	Sprite98: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite99: class extends self.ISpriteInstance {},
	SpeechRecognition: class extends self.IInstance {},
	Sprite100: class extends self.ISpriteInstance {},
	Text17: class extends self.ITextInstance {},
	Sprite101: class extends self.ISpriteInstance {},
	Sprite102: class extends self.ISpriteInstance {},
	Sprite121: class extends self.ISpriteInstance {},
	Sprite122: class extends self.ISpriteInstance {},
	Text18: class extends self.ITextInstance {},
	Sprite125: class extends self.ISpriteInstance {},
	Sprite126: class extends self.ISpriteInstance {},
	Sprite127: class extends self.ISpriteInstance {},
	Sprite128: class extends self.ISpriteInstance {},
	Sprite129: class extends self.ISpriteInstance {},
	Text19: class extends self.ITextInstance {},
	Sprite130: class extends self.ISpriteInstance {},
	Sprite131: class extends self.ISpriteInstance {},
	Sprite132: class extends self.ISpriteInstance {},
	Text20: class extends self.ITextInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite103: class extends self.ISpriteInstance {},
	Sprite104: class extends self.ISpriteInstance {},
	Sprite116: class extends self.ISpriteInstance {},
	history3: class extends self.ISpriteInstance {},
	history4: class extends self.ISpriteInstance {},
	history1: class extends self.ISpriteInstance {},
	history2: class extends self.ISpriteInstance {},
	BG_ALL: class extends self.ISpriteInstance {},
	Sprite142: class extends self.ISpriteInstance {},
	Sprite143: class extends self.ISpriteInstance {},
	Sprite144: class extends self.ISpriteInstance {},
	JSON: class extends self.IJSONInstance {},
	Text21: class extends self.ITextInstance {},
	TextBox_anser: class extends self.ITextInstance {},
	WebSocketDict: class extends self.IDictionaryInstance {},
	Debug_AJAX_Status: class extends self.ITextInstance {},
	Text_AJAX_LastData: class extends self.ITextInstance {},
	Text_Text_Result: class extends self.ITextInstance {},
	Sprite138: class extends self.ISpriteInstance {},
	shop00: class extends self.ISpriteInstance {},
	shop05: class extends self.ISpriteInstance {},
	shop03: class extends self.ISpriteInstance {},
	shop04: class extends self.ISpriteInstance {},
	shop01: class extends self.ISpriteInstance {},
	shop02: class extends self.ISpriteInstance {},
	Sprite149: class extends self.ISpriteInstance {},
	Sprite150: class extends self.ISpriteInstance {},
	Sprite151: class extends self.ISpriteInstance {},
	p1: class extends self.ISpriteInstance {},
	p2: class extends self.ISpriteInstance {},
	p5: class extends self.ISpriteInstance {},
	p4: class extends self.ISpriteInstance {},
	p3: class extends self.ISpriteInstance {},
	shop06: class extends self.ISpriteInstance {},
	Sprite158: class extends self.ISpriteInstance {},
	Sprite140: class extends self.ISpriteInstance {},
	TiledBackground20: class extends self.ITiledBackgroundInstance {},
	Sprite145: class extends self.ISpriteInstance {},
	Sprite146: class extends self.ISpriteInstance {},
	Sprite147: class extends self.ISpriteInstance {},
	Sprite148: class extends self.ISpriteInstance {},
	Sprite159: class extends self.ISpriteInstance {},
	WebSocket: class extends self.IInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	personbutton: class extends self.ISpriteInstance {},
	bookbutton: class extends self.ISpriteInstance {},
	teambutton: class extends self.ISpriteInstance {},
	homebutton: class extends self.ISpriteInstance {},
	notebutton: class extends self.ISpriteInstance {},
	HTMLElement: class extends self.IHTMLElementInstance {},
	HTMLElement2: class extends self.IHTMLElementInstance {},
	TiledBackground21: class extends self.ITiledBackgroundInstance {},
	Text22: class extends self.ITextInstance {},
	Sprite160: class extends self.ISpriteInstance {},
	Sprite161: class extends self.ISpriteInstance {},
	Sentencesnext2: class extends self.ISpriteInstance {},
	Sprite137: class extends self.ISpriteInstance {},
	school_introtext: class extends self.ITextInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Array_choose: class extends self.IArrayInstance {},
	Sprite162: class extends self.ISpriteInstance {},
	Sprite163: class extends self.ISpriteInstance {},
	Sprite164: class extends self.ISpriteInstance {},
	Sprite165: class extends self.ISpriteInstance {},
	Sprite166: class extends self.ISpriteInstance {},
	Sprite167: class extends self.ISpriteInstance {},
	Sprite168: class extends self.ISpriteInstance {},
	Sprite169: class extends self.ISpriteInstance {},
	Sprite170: class extends self.ISpriteInstance {},
	Sprite171: class extends self.ISpriteInstance {},
	Sprite172: class extends self.ISpriteInstance {},
	Sprite173: class extends self.ISpriteInstance {},
	Sprite174: class extends self.ISpriteInstance {},
	Sprite175: class extends self.ISpriteInstance {},
	Sprite176: class extends self.ISpriteInstance {},
	Sprite177: class extends self.ISpriteInstance {},
	Text23: class extends self.ITextInstance {},
	TiledBackground22: class extends self.ITiledBackgroundInstance {},
	Sprite178: class extends self.ISpriteInstance {},
	Sprite179: class extends self.ISpriteInstance {},
	Sprite180: class extends self.ISpriteInstance {},
	Sprite181: class extends self.ISpriteInstance {},
	Sprite182: class extends self.ISpriteInstance {},
	Sprite183_ButtonVocabulary: class extends self.ISpriteInstance {},
	Sprite184_ButtonGrammar: class extends self.ISpriteInstance {},
	Sprite185_ButtonSituation: class extends self.ISpriteInstance {},
	TextVocabulary: class extends self.ITextInstance {},
	TextGrammar: class extends self.ITextInstance {},
	Text24: class extends self.ITextInstance {},
	Text25: class extends self.ITextInstance {},
	ppt: class extends self.ISpriteInstance {},
	Sprite184: class extends self.ISpriteInstance {},
	Sprite185: class extends self.ISpriteInstance {},
	Sprite186: class extends self.ISpriteInstance {},
	Sprite188: class extends self.ISpriteInstance {},
	NoteText: class extends self.ITextInstance {},
	Sprite189: class extends self.ISpriteInstance {},
	Sprite190: class extends self.ISpriteInstance {},
	Sprite191: class extends self.ISpriteInstance {},
	Sprite192: class extends self.ISpriteInstance {},
	Sprite193: class extends self.ISpriteInstance {},
	Sprite133: class extends self.ISpriteInstance {},
	Sprite134: class extends self.ISpriteInstance {},
	Sprite135: class extends self.ISpriteInstance {},
	Sprite136: class extends self.ISpriteInstance {},
	Coin1: class extends self.ISpriteInstance {},
	Sprite194: class extends self.ISpriteInstance {},
	Sprite195: class extends self.ISpriteInstance {},
	Sprite196: class extends self.ISpriteInstance {},
	Sprite197: class extends self.ISpriteInstance {},
	Sprite187: class extends self.ISpriteInstance {},
	Sprite198: class extends self.ISpriteInstance {},
	p6: class extends self.ISpriteInstance {},
	chose3: class extends self.ITextInstance {},
	Sprite152: class extends self.ISpriteInstance {},
	Sprite153: class extends self.ISpriteInstance {},
	Sprite154: class extends self.ISpriteInstance {},
	foodchose11: class extends self.ISpriteInstance {},
	foodchose12: class extends self.ISpriteInstance {},
	foodchose13: class extends self.ISpriteInstance {},
	foodchose14: class extends self.ISpriteInstance {},
	foodchose15: class extends self.ISpriteInstance {},
	foodchose16: class extends self.ISpriteInstance {},
	foodchose21: class extends self.ISpriteInstance {},
	foodchose22: class extends self.ISpriteInstance {},
	foodchose23: class extends self.ISpriteInstance {},
	foodchose24: class extends self.ISpriteInstance {},
	foodchose25: class extends self.ISpriteInstance {},
	foodchose26: class extends self.ISpriteInstance {},
	foodchose31: class extends self.ISpriteInstance {},
	foodchose32: class extends self.ISpriteInstance {},
	foodchose33: class extends self.ISpriteInstance {},
	foodchose34: class extends self.ISpriteInstance {},
	foodchose35: class extends self.ISpriteInstance {},
	foodchose36: class extends self.ISpriteInstance {},
	foodchose41: class extends self.ISpriteInstance {},
	foodchose42: class extends self.ISpriteInstance {},
	foodchose43: class extends self.ISpriteInstance {},
	foodchose44: class extends self.ISpriteInstance {},
	foodchose45: class extends self.ISpriteInstance {},
	foodchose46: class extends self.ISpriteInstance {},
	foodchose51: class extends self.ISpriteInstance {},
	foodchose52: class extends self.ISpriteInstance {},
	foodchose53: class extends self.ISpriteInstance {},
	foodchose54: class extends self.ISpriteInstance {},
	foodchose55: class extends self.ISpriteInstance {},
	foodchose56: class extends self.ISpriteInstance {},
	chose4: class extends self.ITextInstance {},
	chose5: class extends self.ITextInstance {},
	chose6: class extends self.ITextInstance {},
	D_L1: class extends self.ISpriteInstance {},
	Sprite155: class extends self.ISpriteInstance {},
	Sprite156: class extends self.ISpriteInstance {},
	Text11_EN: class extends self.ITextInstance {},
	Text26: class extends self.ITextInstance {},
	notepage: class extends self.ISpriteInstance {},
	Sprite208: class extends self.ISpriteInstance {},
	shop1: class extends self.ISpriteInstance {},
	Sprite209: class extends self.ISpriteInstance {},
	Sprite210: class extends self.ISpriteInstance {},
	foodchose17: class extends self.ISpriteInstance {},
	foodchose18: class extends self.ISpriteInstance {},
	Sprite207: class extends self.ISpriteInstance {},
	drink_suger0: class extends self.ISpriteInstance {},
	drink_ice0: class extends self.ISpriteInstance {},
	drink_suger1: class extends self.ISpriteInstance {},
	drink_suger2: class extends self.ISpriteInstance {},
	drink_suger3: class extends self.ISpriteInstance {},
	drink_suger4: class extends self.ISpriteInstance {},
	drink_ice1: class extends self.ISpriteInstance {},
	drink_ice2: class extends self.ISpriteInstance {},
	drink_ice3: class extends self.ISpriteInstance {},
	drink_ice4: class extends self.ISpriteInstance {},
	Text27: class extends self.ITextInstance {},
	Text28: class extends self.ITextInstance {},
	Sprite183: class extends self.ISpriteInstance {},
	Sprite211: class extends self.ISpriteInstance {},
	Sprite212: class extends self.ISpriteInstance {},
	Text11_CH2: class extends self.ITextInstance {},
	ppt1: class extends self.ISpriteInstance {},
	ppt2: class extends self.ISpriteInstance {},
	ppt3: class extends self.ISpriteInstance {},
	ppt4: class extends self.ISpriteInstance {},
	ppt5: class extends self.ISpriteInstance {},
	ppt6: class extends self.ISpriteInstance {},
	ppt7: class extends self.ISpriteInstance {},
	ppt8: class extends self.ISpriteInstance {},
	ppt9: class extends self.ISpriteInstance {},
	mission_title: class extends self.ITextInstance {},
	pronunce: class extends self.ITextInstance {},
	Sprite213: class extends self.ISpriteInstance {},
	opentext2: class extends self.ITextInstance {},
	SentencesText2: class extends self.ITextInstance {},
	Text11_CH3: class extends self.ITextInstance {},
	Text11_CH4: class extends self.ITextInstance {},
	Text11_CH5: class extends self.ITextInstance {},
	Sprite214: class extends self.ISpriteInstance {},
	missionbox: class extends self.ISpriteInstance {},
	Video2: class extends self.IWorldInstance {},
	missioncompleted_box2: class extends self.ISpriteInstance {},
	joy: class extends self.ISpriteInstance {},
	Options_people: class extends self.ISpriteInstance {},
	Options_trans: class extends self.ISpriteInstance {},
	Options_cards: class extends self.ISpriteInstance {},
	Options_money: class extends self.ISpriteInstance {},
	Options_doors: class extends self.ISpriteInstance {},
	Missions: class extends self.ISpriteInstance {},
	foods: class extends self.ISpriteInstance {}
}